ingressClass:
  fallbackApiVersion: "v1"

service:
  enabled: true
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: default

ports:
  websecure:
    tls: 
      enabled: true  

logs:
  access:
    enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
  kubernetesIngress:
    publishedService:
      enabled: true

additionalArguments:
  - "--metrics.prometheus=true"
{{- if (.Values.ingress).cors }}
  - "--entrypoints.websecure.http.middlewares=default-cors-middleware@kubernetescrd"
{{- end }}
