server:
  configEnabled: true
  config:
    url: https://argocd.{{ .Values.domain }}
    admin.enabled: 'true'
    configManagementPlugins: |
      - name: helm-overdrive
        generate:
          command: ["helm-overdrive"]
          args: ["template", "-c", "./helm-overdrive.yaml" ]

repoServer:
  volumes:
    - name: custom-tools
      emptyDir: {}
  initContainers:
    - name: download-helm-overdrive
      image: alpine:3.8
      command: [sh, -c]
      args:
        - wget -qO- https://github.com/distributed-technologies/helm-overdrive/releases/download/0.0.7/helm-overdrive.linux-amd64.tar.gz | tar -xvzf - && 
          mv helm-overdrive /custom-tools/helm-overdrive
      volumeMounts:
      - mountPath: /custom-tools
        name: custom-tools
  volumeMounts:
    - mountPath: /usr/local/bin/helm-overdrive
      name: custom-tools
      subPath: helm-overdrive
