apiVersion: v1
kind: Namespace
metadata:
  name: networking
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/MartinSchmidt/talos-test.git
    targetRevision: main
    path: . 
    plugin:
      name: helm-overdrive
      env:
        - name: HO_APPLICATION_FOLDER
          value: services/metallb
        - name: HO_HELM_REPO
          value: https://metallb.github.io/metallb
        - name: HO_CHART_NAME
          value: metallb
        - name: HO_CHART_VERSION
          value: 0.12.1
